### ISSUE TITLE
Schematics: Check copy:schematics task by CI

### ISSUE THREAD

**Issue by kouMatsumoto** [ngrx/platform#1214]
## Other information:
Now, we must run `yarn copy:schematics` after modifying files in the schematics-core folder but we can merge pull request without it.
So I suggest add CI diff check job such as the following code.

```
diff-check:
  docker:
    - image: circleci/node:latest-browsers
  steps:
    - checkout
    - restore_cache:
        key: *cache_key
    - run: yarn
    - run: yarn copy:schematics
    - run: git diff --exit-code .
```

Please consider this change, thank you.

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No
