### ISSUE TITLE
Docs: Suggestion to use Labeler

### ISSUE THREAD

**Issue by BioPhoton** [ngrx/platform#2576]
I thought I open an issue for that as I believe it can save the team a lot of work.

https://github.com/actions/labeler

If this is interesting I would contribute with the workflow file.

Just let me know what you think.

**Comment by timdeschryver** [comment]
I like it, I think this can be a great help to filter out PRs 👍

**Comment by BioPhoton** [comment]
Nice!
I'll see what I can do.
😁

**Comment by BioPhoton** [comment]
@brandonroberts @timdeschryver 
Let me know how to proceed.

I would add the following things to the .github folder:

```
.github
  - labeler.yml
  workflows
    - label.yml
```

**labeler.yml**
```yml
# Add 'Project: ngrx.io' label to any ngrx.io file changes
  'Project: ngrx.io':
     - projets/ngrx.io/*
     - projets/ngrx.io/**/*

# Add 'Project: Example App' label to any example-app file changes
  'Project: Example App':
    - projets/example-app/*
    - projets/example-app/**/*

# Add 'Project: Component' label to any change within the 'component' package
  'Project: Component':
     - modules/component/*
     - modules/component/**/*

# Add 'Project: Component Store' label to any change within the 'component-store' package
  'Project: Component Store':
     - modules/component-store/*
     - modules/component-store/**/*

# Add 'Project: Data' label to any change within the 'data' package
  'Project: Data':
    - modules/data/*
    - modules/data/**/*

# Add 'Project: Effects' label to any change within the 'effects' package
  'Project: Effects':
    - modules/effects/*
    - modules/effects/**/*

# Add 'Project: Router Store' label to any change within the 'router-store' package
  'Project: Router Store':
    - modules/data/*
    - modules/data/**/*

# Add 'Project: Schematics' label to any change within the 'schematics' package
  'Project: Schematics':
    - modules/schematics/*
    - modules/schematics/**/*

# Add 'Project: Store' label to any change within the 'store' package
  'Project: Store':
    - modules/store/*
    - modules/store/**/*

# Add 'Project: Store Devtools' label to any change within the 'store-devtools' package
  'Project: Store Devtools':
    - modules/store-devtools/*
    - modules/store-devtools/**/*

# Add 'dependencies' label to any change to npm or yarn related stuff
  dependencies:
     - package.json
     - yarn.lock
```

**label.yml**
```yml
# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# The used configurations are set up in .github/labeler.yml
# For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```
